AWSTemplateFormatVersion: 2010-09-09

Description: VPC cloudformation template

Resources:
  SimpleVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: false
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: SimpleVPC

  SimpleInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: SimpleInternetGateway

  SimpleAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref SimpleVPC
      InternetGatewayId: !Ref SimpleInternetGateway

  SimplePublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SimpleVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, {'Fn::GetAZs': !Ref 'AWS::Region'}]
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: SimplePublicSubnet1

  SimplePrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SimpleVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [0, {'Fn::GetAZs': !Ref 'AWS::Region'}]
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: SimplePrivateSubnet1

  SimplePublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SimpleVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [1, {'Fn::GetAZs': !Ref 'AWS::Region'}]
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: SimplePublicSubnet2

  SimplePrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SimpleVPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: !Select [1, {'Fn::GetAZs': !Ref 'AWS::Region'}]
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: SimplePrivateSubnet2

  SimpleRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SimpleVPC
      Tags:
      - Key: Name
        Value: SimpleRouteTable

  SimpleDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: SimpleAttachGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref SimpleRouteTable
      GatewayId: !Ref SimpleInternetGateway

  SimplePublicSubnet1RTA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SimpleRouteTable
      SubnetId: !Ref SimplePublicSubnet1

  SimplePublicSubnet2RTA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SimpleRouteTable
      SubnetId: !Ref SimplePublicSubnet2

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref SimpleVPC
    Export:
      Name: !Sub ${AWS::StackName}-VPC

  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref SimplePublicSubnet1
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet1

  PublicSubnet2:
    Description: A reference to the public subnet in the 2nd Availability Zone
    Value: !Ref SimplePublicSubnet2
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet2