AWSTemplateFormatVersion: "2010-09-09"
Description: IAM cloudformation template

Resources:
  InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: devops
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:Get*"
                Resource: 'arn:aws:s3:::simpleawsarchitecture-artifacts/*'
              - Effect: Allow
                Action:
                  - "s3:List*"
                Resource: 'arn:aws:s3:::simpleawsarchitecture-artifacts'

  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole

Outputs:
  EC2InstanceProfile:
    Description: EC2 Instance Profile
    Value: !Ref EC2InstanceProfile
    Export:
      Name: !Sub ${AWS::StackName}-EC2InstanceProfile