AWSTemplateFormatVersion: 2010-09-09

Description: Asg cloudformation template

Parameters:
  VpcStackName:
    Type: String
    Description: Name of the VPC stack
    MinLength: 1
    MaxLength: 255
  SecurityGroupStackName:
    Type: String
    Description: Name of the Security Group stack
    MinLength: 1
    MaxLength: 255
  AlbStackName:
    Type: String
    Description: Name of the ALB stack
    MinLength: 1
    MaxLength: 255
  IamStackName:
    Type: String
    Description: EC2 instance profile
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket
    MinLength: 1
    MaxLength: 255

Resources:
  SimpleLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
        - Ebs:
            VolumeSize: 8
            VolumeType: gp3
            DeleteOnTermination: true
            Encrypted: true
          DeviceName: /dev/xvdcz
        ImageId: ami-0005e0cfe09cc9050
        IamInstanceProfile:
          Name:
            Fn::ImportValue: !Sub ${IamStackName}-EC2InstanceProfile
        InstanceType: t2.micro
        Monitoring:
          Enabled: false
        SecurityGroupIds:
        - Fn::ImportValue: !Sub ${SecurityGroupStackName}-SecurityGroupInstances
        UserData:
          Fn::Base64: !Sub |
              #!/bin/bash
              yum update -y 
              yum install -y httpd
              systemctl start httpd
              systemctl enable httpd
              echo "<h1>Hola mundo desde $(hostname -f)</h1>" > /var/www/html/index.html
      LaunchTemplateName: SimpleLaunchTemplate
      TagSpecifications:
      - ResourceType: "launch-template"
        Tags:
        - Key: "Stack"
          Value: "Development"
      VersionDescription: 1.0

  SimpleAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: SimpleAutoScalingGroup
      DesiredCapacity: 1
      MaxSize: 1
      MinSize: 1
      LaunchTemplate:
        LaunchTemplateId: !Ref SimpleLaunchTemplate
        Version: !GetAtt SimpleLaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
      - Fn::ImportValue: !Sub ${VpcStackName}-PublicSubnet1
      - Fn::ImportValue: !Sub ${VpcStackName}-PublicSubnet2
      TargetGroupARNs:
      - Fn::ImportValue: !Sub ${AlbStackName}-TargetGroup